server:
  port: 8080
  timeout: 5s
  readTimeout: 5s
  writeTimeout: 10s
jwt:
  secret: secret-key
  sessionTime: 86400s
db:
  #dataSourceName: root:password@tcp(db)/local_db?charset=utf8&parseTime=True&multiStatements=true
  dataSourceName: root:password@(localhost:43306)/local_db?charset=utf8&parseTime=True&multiStatements=true
  migrate:
    enable: false
    dir: migrations/
  pool:
    maxOpen: 50
    maxIdle: 5
    maxLifetime: 86400s