version: '3.1'

services:
  db:
    image: mysql:8.0.17
    container_name: db
    command: [ '--default-authentication-plugin=mysql_native_password', '--default-storage-engine=innodb' ]
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=local_db
    ports:
      - 43306:3306
    hostname: db